### ISSUE TITLE
updated ubuntu and now get an error

### ISSUE THREAD

**Issue by retropieuser** [NikPiermafrost/rpi5-ubuntu-server-fan-script#2]
So I foolishly updated ubuntu and now I get this error with your script:-

```
pi@pi:~/rpi5-ubuntu-server-fan-script$ ./fan_script.sh
VCHI initialization failed
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
pi@pi:~/rpi5-ubuntu-server-fan-script$ 
```

Any ideas? Or I'm going to need to start with a fresh install?

**Comment by NikPiermafrost** [comment]
Searching online, it might be that vcgencmd requires the "video" group to your user.
This tool is meant to run with root priviledges (since it requires to set the state of the fan). I found [this link](https://helloraspberrypi.blogspot.com/2020/11/run-vcgencmd-on-ubuntu-for-raspberry-pi.html), and even if this is ubuntu desktop it works even with server. This is entirely a guess work so:
- try to run it with root priviledges
- try to add the video group to your user
Remember also that the script is meant to run in a cronjob, not as a one-shot execution

**Comment by NikPiermafrost** [comment]
Closed for inactivity
